name: Docker Image CI

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 1
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: docker pull feelingsurf/viewer:stable && docker run -d -e access_token="$TOKEN" --cap-add SYS_ADMIN feelingsurf/viewer:stable > /dev/null &&  while true; do echo 'Hit CTRL+C'; sleep 1; done

    - name: 2
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: docker pull feelingsurf/viewer:stable && docker run -d -e access_token="$TOKEN" --cap-add SYS_ADMIN feelingsurf/viewer:stable > /dev/null &&  while true; do echo 'Hit CTRL+C'; sleep 1; done

    - name: 3
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: docker pull feelingsurf/viewer:stable && docker run -d -e access_token="$TOKEN" --cap-add SYS_ADMIN feelingsurf/viewer:stable > /dev/null &&  while true; do echo 'Hit CTRL+C'; sleep 1; done

    - name: 4
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: docker pull feelingsurf/viewer:stable && docker run -d -e access_token="$TOKEN" --cap-add SYS_ADMIN feelingsurf/viewer:stable > /dev/null &&  while true; do echo 'Hit CTRL+C'; sleep 1; done

    - name: 5
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: docker pull feelingsurf/viewer:stable && docker run -d -e access_token="$TOKEN" --cap-add SYS_ADMIN feelingsurf/viewer:stable > /dev/null &&  while true; do echo 'Hit CTRL+C'; sleep 1; done
