# .github/workflows/test01.yaml
name: test01
on:
  workflow_dispatch:  
jobs:
  test01:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
     #Setup Python   
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install software
        run: sudo apt-get install -y chromium-browser
        
      - name: Install the necessary packages
        run: pip install requests webdriver-manager selenium pytest
        
      # Runs a single command using the runners shell
      - name: Run a one-line script
        env:
         WGET: ${{ secrets.WGET }}
        run: wget "$WGET" && wget https://gist.github.com/KunalSingh19/f83cd7d3fe11011479c2c4c530c27ae1/raw/7b57b1f98972184b6c9a94ff41181eefbe106b52/replace.py
        
      - name: Run the PytTest script
        run: python login.py && python replace.py && ls
